kumishida/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include, handler404, handler500
from shortener import views
from qr_code import urls as qr_code_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^(?P<shortcode>[\w-]+)/$', views.redirect_url, name='redirect_url'),
    url(r'^shortener/', include('shortener.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),
]

handler404 = views.error404
handler500 = views.error500

shortener/urls.py
from django.conf.urls import url
from . import views

app_name = 'shortener'

urlpatterns = [
    url(r'^(?P<shortcode>[\w-]+)$', views.get_click_count, name='get_click_count'),
    url(r'^change/(?P<shortcode>[\w-]+)/$', views.change_status, name='change_status'),
]

user/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views

app_name = 'user'

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', LoginView.as_view(template_name='user/login.html',
                                       redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^tracking/$', views.tracking, name='tracking'),
    url(r'^delete/(?P<shortcode>[\w-]+)/$', views.delete_url, name='delete_url'),
]

shortener/models.py
from django.db import models
from .utils import code_generator, create_shortcode
from django.contrib.auth.models import User


class URLManager(models.Manager):
    def refresh_codes(self, *args, **kwargs):
        query_set = URL.objects.all()
        new_codes = 0
        for q in query_set:
            q.short_code = create_shortcode(q)
            q.save()
            new_codes += 1
        return "New codes made: {i}".format(i=new_codes)


class URL(models.Model):
    STATUS_CHOICE = (
        ('public', 'Public'),
        ('private', 'Private'),
    )
    url = models.CharField(max_length=220)
    short_code = models.CharField(
        max_length=15, unique=True, null=False, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='public')
    user = models.ForeignKey(User, related_name='user', blank=True, null=True, on_delete=models.CASCADE)
    objects = URLManager()

    def __str__(self):
        return str(self.url)

    def save(self, *args, **kwargs):
        if self.short_code == "" or self.short_code is None:
            self.short_code = create_shortcode(self)
        super(URL, self).save(*args, **kwargs)

    def get_short_url(self):
        return "http://127.0.0.1:8000/{shortcode}".format(shortcode=self.short_code)

shortener/forms.py
from django import forms
from .models import URL


class URLForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = URL
        fields = ('url',)
        widgets = {
            'url': forms.URLInput(attrs={'type': 'text', 'class': 'form-control', 'placeholder': 'Your original url here', 'autocomplete': 'off', 'autofocus': ''})
        }

shortener/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http.response import JsonResponse
from django.contrib.auth.decorators import login_required
from analytics.models import ClickCount
from .forms import URLForm
from .models import URL
from .utils import validate_url

def index(request):
    valid = True
    form = URLForm()
    if request.method == "POST":
        try:
            validate_url(request.POST['url'])
        except ValidationError:
            valid = False
        else:
            valid = True
            form = URLForm(request.POST)
            if form.is_valid():
                obj = URL()
                obj.url = form.cleaned_data['url']
                #if user is logged in
                if request.user.id:
                    obj.user = request.user
                obj.save()
                ClickCount.objects.create_event(obj)
                return redirect('/')
            else:
                valid = False
    urls = URL.objects.all().filter(status__exact='public').order_by('-timestamp')
    paginator = Paginator(urls, 10)
    page = request.GET.get('page')
    urls_display = paginator.get_page(page)
    return render(request, 'shortener/index.html', {'form': form, 'valid': valid, 'urls_display': urls_display})

def redirect_url(request, shortcode):
    try:
        url = get_object_or_404(URL, short_code=shortcode)
    except:
        return render(request, 'shortener/404.html')
    else:
        ClickCount.objects.create_event(url)
        trueurl = url.url
        if trueurl.find('http') == -1:
            trueurl = 'https://' + trueurl
        return redirect(trueurl)

def get_click_count(request, shortcode):
    if request.method == 'GET':
        try:
            url = get_object_or_404(URL, short_code=shortcode)
        except:
            return JsonResponse({'clickcount': -1})
        else:        
            clickcount = ClickCount.objects.create_event(url)
            return JsonResponse({'clickcount': clickcount})
    
def error404(request):
    return render(request, 'shortener/404.html')

def error500(request):
    return render(request, 'shortener/500.html')

@login_required
def change_status(request, shortcode):
    try:
        url = get_object_or_404(URL, short_code=shortcode)
    except:
        return JsonResponse({'status': 'undefined'})
    else:
        if request.user.is_authenticated:
            if url.status == 'public':
                url.status = 'private'
            else:
                url.status = 'public'
            url.save()
            return JsonResponse({'status': url.status})
        else:
            return JsonResponse({'status': url.status})

shortener/templates/shortener/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
    {% block styles %}
    {% endblock %}
    <title>URL Shorten Service</title>
</head>

<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light p-md-8" style="background-color: #fff;">
            <a class="navbar-brand" href="/">
                <img src="{% static "img/goo_gl.svg" %}" alt="Logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">
                            <span class="text-muted" style="font-size: 1.375em;">URL Shortener</span>
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <div class="dropdown">
                            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButtonUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: #fff;">
                            Welcome, {{user.username}}
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButtonUser">
                                <a class="dropdown-item" href="/user/tracking">Tracking</a>
                                <a class="dropdown-item" href="{% url 'user:logout' %}">Sign out</a>
                            </div>
                        </div>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:login' %}">
                                <span class="text-muted">Login</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:signup' %}">
                                <span class="text-muted">Sign Up</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
    {% block scripts %}
    {% endblock %}
</body>

</html>

shortener/templates/shortener/index.html
{% extends 'shortener/base.html' %}

{% block content %}
<div class="row">
    <div class="col pt-4 pb-5 text-white form-shortener">
        <div class="shortener">
            <h2 class="font-weight-light">Simplify your links</h2>
            <form method="POST">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-10">
                        {% for field in form.visible_fields %} {{ field }} {% endfor %}
                    </div>
                    <div class="form-group col-md-2">
                        <button type="submit" class="btn btn-outline-light">Shorten URL</button>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {% if valid is not True %}
                        <script>
                            document.getElementsByClassName('form-control')[0].className += " is-invalid"
                        </script>
                        <div class="invalid-feedback" style="display: block !important;">
                            Invalid URL for this field.
                        </div>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row mt-3">
    <div class="table-responsive text-secondary list-link">
        <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Original URL</th>
                    <th scope="col">Created</th>
                    <th scope="col">Short URL</th>
                    <th scope="col">All Clicks</th>
                </tr>
            </thead>
            <tbody>
                {% for url in urls_display %}
                <tr>
                    <td scope="row">
                        <a href="{{ url.url }}" target="_blank">{{ url.url|truncatechars:50 }}</a>
                    </td>
                    <td>{{ url.timestamp }}</td>
                    <td>
                        <a onclick="getClickCount(this);" class="{{ url.short_code }}" href="{{ url.get_short_url }}" target="_blank">rutgonlink.herokuapp.com/{{url.short_code}}</a>
                    </td>
                    <td class="{{ url.short_code }}">{{ url.clickcount.count }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col">
        <nav>
            <ul class="pagination justify-content-center">
                {% if urls_display.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                {% endif %}
                <li class="page-item active">
                    <a class="page-link" href="javascript:;">{{ urls_display.number }}
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                {% if urls_display.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ urls_display.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    function getClickCount(e){
        $.ajax({
            method: 'GET',
            url: '/shortener/' + e.className,
            success: (data) => {
                e.parentElement.parentElement.getElementsByTagName('td')[3].innerHTML = data['clickcount'];
            },
            error: (error) => {
                console.log(error);
            }
        });
    }
</script>
{% endblock %}