kumishida/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include, handler404, handler500
from shortener import views
from qr_code import urls as qr_code_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^(?P<shortcode>[\w-]+)/$', views.redirect_url, name='redirect_url'),
    url(r'^shortener/', include('shortener.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),
]

handler404 = views.error404
handler500 = views.error500

user/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views

app_name = 'user'

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', LoginView.as_view(template_name='user/login.html',
                                       redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^tracking/$', views.tracking, name='tracking'),
    url(r'^delete/(?P<shortcode>[\w-]+)/$', views.delete_url, name='delete_url'),
]

user/models.py
from django.db import models

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="Email address", max_length=254,
                             help_text="Required. Inform a valid email address.", required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.email = self.cleaned_data.get('email')
        if commit:
            user.save()
        return user

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from shortener.views import index
from shortener.models import URL
from .forms import UserForm


def logout_view(request):
    logout(request)
    return redirect('/')

def signup(request):
    if not request.user.is_authenticated:
        if request.method != 'POST':
            form = UserForm()
        else:
            form = UserForm(data=request.POST)
            if form.is_valid():
                newUser = form.save()
                authenticated_user = authenticate(username=newUser.username, password=request.POST.get('password1'))
                login(request, authenticated_user)
                return redirect('/')
        return render(request, 'user/signup.html', {'form': form})
    else:   
        return redirect('/')

def login_view(request):
    print(request.user.is_authenticated)
    if request.user.is_authenticated:
        return redirect('/')
    else:
        return login(request, 'user/login.html')

@login_required
def tracking(request):
    urls = URL.objects.filter(user__exact=request.user).order_by('-timestamp')
    paginator = Paginator(urls, 10)
    page = request.GET.get('page')
    urls_display = paginator.get_page(page)
    return render(request, 'user/tracking.html', {'urls_display': urls_display})

@login_required
def delete_url(request, shortcode):
    try:
        url = get_object_or_404(URL, short_code=shortcode, user=request.user)
    except:
        return render(request, 'shortener/404.html')
    else:
        url.delete()
        return redirect('user:tracking')

user/templates/user/login.html
{% extends 'shortener/base.html' %}
{% block content %}
<div class="row">
    <div class="col col-md-6 offset-md-3">
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
        {% endfor %}
    </div>
</div>
<div class="row">
    <div class="col col-md-4 offset-md-4">
        <form id="form" method="POST" action="{% url 'user:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Username</label>
                <input type="text" class="form-control" name="username" maxlength="150" autofocus required id="id_username" autocomplete="off">
            </div>
            <div class="form-group">
                <label for="id_password">Password</label>
                <input type="password" class="form-control" name="password" required autocomplete="off" id="id_password">
                {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <small class="form-text text-danger">{{error}}</small>
                    {% endfor %}
                {% endif %}
            </div>
            <input type="hidden" name="next" value="{{ next }}">
            <button type="submit" class="btn btn-outline-primary" value="submit">Login</button> 
        </form>
    </div>
</div>
{% endblock %}

user/templates/user/signup.html
{% extends 'shortener/base.html' %}
{% block content %}
<div class="row">
    <div class="col col-sm-4 offset-sm-4">
        <form id="form" method="POST" action="{% url 'user:signup' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Username</label>
                <input type="text" class="form-control" name="username" maxlength="150" autofocus required id="id_username" autocomplete="off" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
                {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <small class="form-text text-danger">{{error}}</small>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_email">Email</label>
                <input type="email" class="form-control" name="email" maxlength="254" required id="id_email" autocomplete="off" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">Required. Inform a valid email address.</small>
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <small class="form-text text-danger">{{error}}</small>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_password1">Password</label>
                <input type="password" class="form-control" name="password1" required autocomplete="off" id="id_password1">
                {% if form.password1.errors %}
                    {% for error in form.password1.errors %}
                        <small class="form-text text-danger">{{error}}</small>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_password2">Password confirmation</label>
                <input type="password" class="form-control" name="password2" required autocomplete="off" id="id_password2" aria-describedby="password2Help">
                <small id="password2Help" class="form-text text-muted">Enter the same password as before, for verification.</small>
                {% if form.password2.errors %}
                    {% for error in form.password2.errors %}
                        <small class="form-text text-danger">{{error}}</small>
                    {% endfor %}
                {% endif %}
            </div>
            <button type="submit" class="btn btn-outline-primary" value="submit">Signup</button>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function() {
        $('input').focusin(function() {
            var helptext = $(this).next();
            $(helptext).css('display', 'none');
        })

        $('input').focusout(function() {
            var helptext = $(this).next();
            $(helptext).css('display', 'block');
        })
    })
</script>
{% endblock %}

user/templates/user/tracking.html
{% extends 'shortener/base.html' %}
{% load staticfiles %}
{% load qr_code %}

{% block styles %}
    <link rel="stylesheet" href="{% static "css/tracking.css" %}">
{% endblock styles %}

{% block content %}
<div class="row">
    <div class="table-responsive text-secondary list-link">
        <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Original URL</th>
                    <th scope="col">Created</th>
                    <th scope="col">Short URL</th>
                    <th scope="col">State</th>
                    <th scope="col">All Clicks</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for url in urls_display %}
                <tr id="{{ url.short_code }}">
                    <td scope="row">
                        <a href="{{ url.url }}" target="_blank">{{ url.url|truncatechars:50 }}</a>
                    </td>
                    <td>{{ url.timestamp }}</td>
                    <td>
                        <a onclick="getClickCount(this);" class="{{ url.short_code }}" href="{{ url.get_short_url }}" target="_blank">rutgonlink.herokuapp.com/{{url.short_code}}</a>
                    </td>
                    <td>
                        <a onclick="changeStatus(this);" class="{{ url.short_code }} text-secondary" href="javascript:;">{{ url.status|capfirst }}</a>
                    </td>
                    <td>{{ url.clickcount.count }}</td>
                    <td class="text-right">
                        <button class="options-button dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert </i>
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Analysts Data</a>
                            <a class="dropdown-item" data-toggle="modal" href="#modalQRCode_{{ url.short_code }}">QR Code</a>
                            <a class="dropdown-item delete" data-value="{{ url.short_code }}" href="javascript:;">Delete URL</a>
                        </div>
                        <div class="modal fade" id="modalQRCode_{{ url.short_code }}" tabindex="-1" role="dialog" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">QR Code</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body text-center">
                                        <img src="{% qr_url_from_text url.get_short_url size=18 version=4 %}">
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-primary" data-dismiss="modal">Done</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col">
        <nav>
            <ul class="pagination justify-content-center">
                {% if urls_display.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ urls_display.previous_page_number }}">previous</a>
                </li>
                {% endif %}
                <li class="page-item active">
                    <a class="page-link" href="javascript:;">{{ urls_display.number }}
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                {% if urls_display.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ urls_display.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-muted">Delete this link?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger text-center" role="alert">
                    Your link will be removed and cannot accessed in the future!
                </div>
                <p class="h6 text-muted">Short URL</p>
                <p id="short-url">
                    <a href="#"></a>
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn-delete">Delete</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="{% static "js/script.js" %}"></script>
{% endblock %}